### ISSUE TITLE
Найти датасеты по анализу жестов на видео (2)

### ISSUE THREAD

**Issue by Erhil** [megahard25/ChillTeam#2]

**Comment by anton-kuvaldin** [comment]
http://www.nlpr.ia.ac.cn/iva/yfzhang/datasets/egogest..
https://www.idiap.ch/resource/gestures/
http://www.cbsr.ia.ac.cn/users/jwan/database/isogd.html
https://www.overleaf.com/4373659244rqvqrgqbrjmf

**Comment by anton-kuvaldin** [comment]
https://www.overleaf.com/project/5e57a1f52c54d600013be850
