### ISSUE TITLE
Написать скрипты для работы с датасетом на Google Colab (5)

### ISSUE THREAD

**Issue by Erhil** [megahard25/ChillTeam#7]

**Comment by annykay** [comment]
https://colab.research.google.com/drive/17X0_XHeZhUwI3Wg6UV3ncybvUGbbgNhQ#scrollTo=L5f19q-OXWHb

**Comment by anton-kuvaldin** [comment]
https://colab.research.google.com/drive/17X0_XHeZhUwI3Wg6UV3ncybvUGbbgNhQ#scrollTo=ZYnT_HngWRdh
